variables:
  # To make npm test to not to start in watch mode
  # https://create-react-app.dev/docs/running-tests/#continuous-integration
  CI: "true"

cache:
  paths:
    - node_modules/
    - artifacts/
    - cache/

before_script:
  - npm install

stages:
  - test
  - package

lint:
  image: docker.atixlabs.com/node:10.15.3
  stage: test
  script:
    - npm run lint
  except:
    - schedules

test_contracts:
  image: docker.atixlabs.com/node:10.15.3
  stage: test
  script:
    - npm run node > /dev/null &
    - sleep 5
    - npm run test:contracts
  except:
    - schedules

test_be:
  image: docker.atixlabs.com/node:10.15.3
  stage: test
  script:
    - npm run test
  except:
    - schedules

package:
  image: docker.atixlabs.com/node:10.15.3
  stage: package
  services:
    - docker.atixlabs.com/docker:19.03.1-dind
  script:
    - apt install docker
    - docker login -u gitlabci -p $CI_JOB_TOKEN $CI_REGISTRY
    - npm run docker:build
    - npm run docker:push
  only:
    refs:
      # Only run on develop, release/x.y.x and hotfix/xxxx
      - develop
      - /^release.*$/
      - /^hotfix.*$/

