CREATE TABLE public.project (
	"id" serial NOT NULL,
	"projectName" varchar(50) NOT NULL,
	"ownerId" int4 NOT NULL,
	"mission" text NOT NULL,
	"problemAddressed" text NOT NULL,
	"location" text NOT NULL,
	"timeframe" text NOT NULL,
	"coverPhoto" int4 NULL,
	"cardPhoto" int4 NULL,
	"status" int2 NOT NULL,
	"goalAmount" float4 NOT NULL,
	"faqLink" varchar NOT NULL,
	"pitchProposal" varchar(100) NULL,
	"createdAt" date NULL,
	"updatedAt" date NULL,
	"projectAgreement" varchar(100) NULL,
	"milestonesFile" varchar(100) NULL,
	CONSTRAINT project_pkey PRIMARY KEY (id),
	CONSTRAINT card_photo_fk FOREIGN KEY ("cardPhoto") REFERENCES photo(id),
	CONSTRAINT cover_photo_fk FOREIGN KEY ("coverPhoto") REFERENCES photo(id)
);
