CREATE TABLE public.milestone (
	"id" serial NOT NULL,
	"projectId" int4 NULL,
	"quarter" text NULL,
	"tasks" text NULL,
	"impact" text NULL,
	"impactCriterion" text NULL,
	"signsOfSuccess" text NULL,
	"signsOfSuccessCriterion" text NULL,
	"category" text NULL,
	"keyPersonnel" text NULL,
	"budget" text NULL,
	"status" int2 NOT NULL,
	"createdAt" date NULL,
	"updatedAt" date NULL,
	"budgetStatus" int4 NOT NULL,
	CONSTRAINT "milestone_pkey" PRIMARY KEY (id),
	CONSTRAINT "milestone_milestone_budget_status_fk" FOREIGN KEY ("budgetStatus") REFERENCES milestone_budget_status(id),
	CONSTRAINT "milestone_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES project(id) ON DELETE CASCADE
);